### ISSUE TITLE
"is local" check fails when used in a wayland session since no method of obtaining the session tty succeeds

### ISSUE THREAD

**Issue by a1ad** [mcdope/pam_usb#81] opened 2021-10-19 14:18 UTC
`[src/local.c:177] Checking whether the caller (pamusb-agent) is local or not...
[src/local.c:187] 	Checking pid   5972 (/usr/bin/pamusb-check)...
[src/local.c:187] 	Checking pid   5744 (bash)...
[src/local.c:187] 	Checking pid   5241 (/usr/libexec/gnome-terminal-server)...
[src/local.c:187] 	Checking pid   2543 (/usr/lib/systemd/systemd)...
[src/local.c:187] 	Checking pid      1 (/usr/lib/systemd/systemd)...
[src/local.c:227] 	Using DISPLAY :0 for utmp search
[src/local.c:047] 	No utmp entry found for tty ":0"
[src/local.c:233] 	Trying to get tty from Xorg process
[src/local.c:244] 	Trying to get tty by DISPLAY
[src/local.c:262] 	Using TTY /dev/pts/0 for search
[src/local.c:047] 	No utmp entry found for tty "pts/0"
[src/local.c:270] Couldn't confirm login tty to be neither local or remote - denying.
* Access denied.
`
Did I miss a config parameter?

`[Jeroen@40083352478 ~]$ w
 16:22:30 up 36 min,  1 user,  load average: 1,23, 0,76, 0,61
USER     TTY        LOGIN@   IDLE   JCPU   PCPU WHAT
Jeroen   tty2      15:47   36:00   0.12s  0.10s /usr/libexec/gnome-session-binary
`

Fedora 35 and Wayland

**Comment by mcdope** [comment] 2021-10-19 16:52
Thanks, was just curious if somebody is building packages

**Comment by mcdope** [comment] 2021-10-30 14:03
![grafik](https://user-images.githubusercontent.com/3312979/139536065-7e510b16-4d28-4875-807c-f283d5f2bea9.png)

Would you please checkout branch #84, build and test? For me it's working but I prefer to get user feedback before merging.

**Comment by a1ad** [comment] 2021-10-30 20:26
```
[Jeroen@40083352478 ~]$ pamusb-check Jeroen
* Authentication request for user "Jeroen" (pamusb-check)
* Access denied.
[Jeroen@40083352478 ~]$ pamusb-check Jeroen -v
pamusb-check: invalid option -- 'v'
Usage: pamusb-check [--help] [--debug] [--config=path] [--service=name] [--dump] [--quiet] [--debug] [--version] <username>
[Jeroen@40083352478 ~]$ pamusb-check Jeroen --debug
* Authentication request for user "Jeroen" (pamusb-check)
[src/local.c:178] Checking whether the caller (pamusb-check) is local or not...
[src/local.c:188] 	Checking pid 306932 (pamusb-check)...
[src/local.c:188] 	Checking pid 306382 (bash)...
[src/local.c:188] 	Checking pid 306364 (/usr/libexec/gnome-terminal-server)...
[src/local.c:188] 	Checking pid   4221 (/usr/lib/systemd/systemd)...
[src/local.c:188] 	Checking pid      1 (/usr/lib/systemd/systemd)...
[src/local.c:237] 	Using DISPLAY :0 for utmp search
[src/local.c:047] 	No utmp entry found for tty ":0"
[src/local.c:250] 	Trying to get tty from display server
[src/local.c:261] 	Trying to get tty by DISPLAY
[src/local.c:279] 	Using TTY /dev/pts/0 for search
[src/local.c:047] 	No utmp entry found for tty "pts/0"
[src/local.c:287] Couldn't confirm login tty to be neither local or remote - denying.
* Access denied.
[Jeroen@40083352478 ~]$ pamusb-check Jeroen --version
Version 0.8.0
```

**Comment by mcdope** [comment] 2021-10-30 21:55
That's unexpected. Will need to setup a Fedora VM then, seems something is different to Wayland on Ubuntu.

**Comment by a1ad** [comment] 2021-10-31 08:09
> That's unexpected. Will need to setup a Fedora VM then, seems something is different to Wayland on Ubuntu.

**Comment by mcdope** [comment] 2021-10-31 12:21
> tested 0.8.1 also without success.

That's to be expected, 0.8.1 branch is just master with updated versioning but does not include #84 yet since it wasn't merged to master so far.

> Be sure to install fedora 35. That is what I am using.

:heavy_check_mark:

**Comment by mcdope** [comment] 2021-11-01 12:14
VM prepared, time to check stuff. 
![image](https://user-images.githubusercontent.com/3312979/139669741-2091852c-4654-4bcc-8f09-21771055429b.png)

Btw, the `cp` steps from your install tutorial aren't required. I've now also added the required devel packages for Fedora to the Wiki now.

**Comment by a1ad** [comment] 2021-11-01 12:54
> VM prepared, time to check stuff. ![image](https://user-images.githubusercontent.com/3312979/139669741-2091852c-4654-4bcc-8f09-21771055429b.png)
> 
> Btw, the `cp` steps from your install tutorial aren't required. I've now also added the required devel packages for Fedora to the Wiki.
> 
> Edit: Hmmm okay, I see why the Ubuntu approach isn't working on Fedora. On Ubuntu gnome-session-binary is launched with fd0 being bound to the session tty while on Fedora that is assigned to /dev/null.

Be careful, you might like the distro 😄

**Comment by mcdope** [comment] 2021-11-01 13:04
> Be careful, you might like the distro smile

Maybe if they switch from rpm to deb, and stop using such wierd package names haha

**Comment by mcdope** [comment] 2021-11-01 13:44
Works in my VM now :)

![image](https://user-images.githubusercontent.com/3312979/139681386-4a55a1c4-126c-4186-a08b-51e1fafd001d.png)


Can you test that branch again please? Make sure to run `make clean` before, just in case.

**Comment by mcdope** [comment] 2021-11-01 13:47
lmao, fml - I've just found the correct process to check on Fedora to make the Ubuntu approach work too :D But guess one can never have to many ways to make it work...

**Comment by a1ad** [comment] 2021-11-01 13:57
so which branch do i need to use now?

**Comment by a1ad** [comment] 2021-11-01 14:01
So... the checked passed but sudo -s is not working??

**Comment by mcdope** [comment] 2021-11-01 14:27
> edit2

That will be caused by sudo caching your manually entered password / auth. Try again after running `sudo -k`, it should't work anymore.

> So... the checked passed but sudo -s is not working?? 

For me pamusb is not invoked at all by sudo and seemingly even PAM. How exactly have you integrated pamusb into your PAM setup? Following my own wiki haven't worked for me it seems. :D

**Comment by mcdope** [comment] 2021-11-01 14:59
sudo working for me, login however is not. 

Is login working for you? If yes, how have you configured it?

**Comment by a1ad** [comment] 2021-11-01 15:11
No its not working here

```
[Jeroen@40083352478 ~]$ sudo -k
[Jeroen@40083352478 ~]$ sudo bash
* Authentication request for user "Jeroen" (sudo)
* Access denied.
[sudo] wachtwoord voor Jeroen: 
^C^Csudo: een wachtwoord is verplicht

[Jeroen@40083352478 ~]$ pamusb-check Jeroen --debug
* Authentication request for user "Jeroen" (pamusb-check)
[src/local.c:211] Checking whether the caller (pamusb-check) is local or not...
[src/local.c:221] 	Checking pid 143242 (pamusb-check)...
[src/local.c:221] 	Checking pid 142059 (bash)...
[src/local.c:221] 	Checking pid 142041 (/usr/libexec/gnome-terminal-server)...
[src/local.c:221] 	Checking pid   3502 (/usr/lib/systemd/systemd)...
[src/local.c:221] 	Checking pid      1 (/usr/lib/systemd/systemd)...
[src/local.c:270] 	Using DISPLAY :0 for utmp search
[src/local.c:047] 	No utmp entry found for tty ":0"
[src/local.c:283] 	Trying to get tty from display server
[src/local.c:288] 	Retrying with tty /dev/tty2, obtained from display server, for utmp search
[src/local.c:050] 		utmp entry for tty "tty2" found
[src/local.c:051] 			utmp->ut_pid: 3541
[src/local.c:052] 			utmp->ut_user: Jeroen
[src/local.c:066] 		Checking utmp->ut_addr_v6[0]
[src/local.c:066] 		Checking utmp->ut_addr_v6[1]
[src/local.c:066] 		Checking utmp->ut_addr_v6[2]
[src/local.c:066] 		Checking utmp->ut_addr_v6[3]
[src/local.c:070] 	utmp check successful, request originates from a local source!
[src/local.c:337] No remote access detected, seems to be local request - allowing.
[src/device.c:038] Searching for "MyKey" in the hardware database...
* Authentication device "MyKey" is connected.
* Performing one time pad verification...
[src/volume.c:097] Searching for volume with uuid D0CD-159C.
[src/volume.c:121] Found mount points: /run/media/Jeroen/D0CD-159C
[src/volume.c:134] Found volume D0CD-159C.
[src/volume.c:158] Volume D0CD-159C is already mounted.
[src/pad.c:261] Loading device pad...
[src/pad.c:263] Loading system pad...
[src/pad.c:269] Pad match.
[src/pad.c:153] Checking whether pads are expired or not...
[src/pad.c:176] Pads expired 584 seconds ago, updating...
* Regenerating new pads...
[src/pad.c:123] Protecting pad file...
[src/pad.c:123] Protecting pad file...
[src/pad.c:218] Generating 1024 bytes unique pad...
[src/pad.c:233] Writing pad to the device...
[src/pad.c:235] Writing pad to the system...
[src/pad.c:237] Synchronizing filesystems...
[src/pad.c:242] One time pads updated.
* Access granted.

[Jeroen@40083352478 ~]$ cat /etc/pam.d/system-auth
# Generated by authselect on Tue Oct 19 10:10:47 2021
# Do not modify this file manually.

auth	    sufficient      				 pam_usb.so

auth        required                                     pam_env.so
.....
[Jeroen@40083352478 ~]$ 
```

**Comment by mcdope** [comment] 2021-11-01 15:27
Weird, however this by now seems to be more about properly installing on Fedora since `pamusb-check` does exactly what the PAM lib does, so if check works - PAM should too. 

What is irritating me that not even `sudo` works for me. For me it works like charm. https://www.dropbox.com/s/psad78iylqz6tea/Peek%202021-11-01%2016-24.gif?dl=0

**Comment by mcdope** [comment] 2021-11-01 15:51
Found why login isn't working, there are actually two PAM config files requiring changes.

If you insert the same line you put into `system-auth` also into `password-auth` (again before pam_unix) the login auth is working, too.

**Comment by a1ad** [comment] 2021-11-01 18:35
Hmm need to test it why its not working here.

**Comment by a1ad** [comment] 2021-11-01 20:08
Yeah! User error indeed, needed to replace the .so in the system manually. It works great now! Can we also unlock the keyring with it? It's a bit annoying that I still need to type the password after login :-)

**Comment by mcdope** [comment] 2021-11-01 21:12
Thanks for the feedback, will merged soon and released tomorrow tthen.

> Can we also unlock the keyring with it?

Dangerous waters, don't even get me started about the keyring stuff >.<

See https://github.com/mcdope/pam_usb/discussions/66 and many other place discussing pam modules and keyring unlock.

It won't happen except someone creates a pullrequest prroviding it. It can be added to the code, but it's a pain. (Create a new keyring, import existing secrets, provide some task or daemon keeping them in sync).

**Closed** 2021-11-01 21:14 UTC
Labels: bug

**Comment by mcdope** [comment] 2021-11-06 16:24
@a1ad Since you asked about it, there is now experimental support for unlocking the keyring. See https://github.com/mcdope/pam_usb/wiki/Getting-Started#auto-unlock-your-gnome-keyring for details. Ofc you would need to build it yourself, branch is `issue-11-provide-optional-unlock-script`.

**Comment by a1ad** [comment] 2021-11-06 17:49
Nice! will test. Can't we put the password on the USB device itself?

**Comment by mcdope** [comment] 2021-11-06 18:35
I've decided against putting it on the device because we can't ensure it can only be read by the owning user there.

RE: copy lib: will add a condition to the makefile somehow, when i find the time to actually test on fedora. Guess a simple check which directory exists will be enough.

**Comment by a1ad** [comment] 2021-11-06 18:45
Yeah fair enough. Its working great here!

**Comment by mcdope** [comment] 2021-11-06 18:49
![grafik](https://user-images.githubusercontent.com/3312979/140620572-2506dae0-350d-4d4a-8f92-f44ed69e4b0a.png)

I can understand that for users sure they keep their auth device safe it may be preferred to store the file on the device anyway... Guess I will add support for both, if it doesn't exist in `~` try again with `/media/whateverTheMountpathIs`.

**Comment by mcdope** [comment] 2021-11-07 11:16
Support for keyfile on auth device was just added in https://github.com/mcdope/pam_usb/pull/93/commits/810ffcc1eec69c5f280cae33c2726cd7fa33b7ec
