### ISSUE TITLE
KDE Plasma lockscreen won't unlock

### ISSUE THREAD

**Issue by steelsnake** [mcdope/pam_usb#181] opened 2022-09-04 11:39 UTC
It appears the KDE Plasma lockscreen doesn't get recognized as being local. Not sure if that;s related to the other issue I submitted. If I can provide any additional information please do let me know.

```
Sep  4 05:31:51 wombat pam_usb[188024]: Authentication request for user "jenni" (kde)
Sep  4 05:31:51 wombat pam_usb[188024]: Checking whether the caller (kde) is local or not...
Sep  4 05:31:51 wombat pam_usb[188024]: #011Checking pid 188024 (kcheckpass)...
Sep  4 05:31:51 wombat pam_usb[188024]: #011Checking pid 187946 (/usr/lib/x86_64-linux-gnu/libexec/kscreenlocker_greet)...
Sep  4 05:31:51 wombat pam_usb[188024]: #011Checking pid 175571 (/usr/bin/ksmserver)...
Sep  4 05:31:51 wombat pam_usb[188024]: #011Checking pid 175506 (/usr/bin/plasma_session)...
Sep  4 05:31:51 wombat pam_usb[188024]: #011Checking pid 175360 (/usr/bin/startplasma-x11)...
Sep  4 05:31:51 wombat pam_usb[188024]: #011Checking pid 175352 (/usr/lib/x86_64-linux-gnu/sddm/sddm-helper)...
Sep  4 05:31:51 wombat pam_usb[188024]: #011Checking pid   1462 (/usr/bin/sddm)...
Sep  4 05:31:51 wombat pam_usb[188024]: #011Checking pid      1 (/sbin/init)...
Sep  4 05:31:51 wombat pam_usb[188024]: #011Using DISPLAY :0 for utmp search
Sep  4 05:31:51 wombat pam_usb[188024]: #011No utmp entry found for tty ":0"
Sep  4 05:31:51 wombat pam_usb[188024]: #011Trying to get tty from display server
Sep  4 05:31:51 wombat pam_usb[188024]: #011#011Failed, no result while trying to get TTY from display server
Sep  4 05:31:51 wombat pam_usb[188024]: #011Trying to get tty by DISPLAY
Sep  4 05:31:51 wombat pam_usb[188024]: #011#011Failed, no result while searching utmp for display :0 owned by user jenni
Sep  4 05:31:51 wombat pam_usb[188024]: #011Trying to get tty by loginctl
Sep  4 05:31:51 wombat pam_usb[188024]: #011#011'loginctl' returned nothing.'
Sep  4 05:31:51 wombat pam_usb[188024]: #011#011Failed, no result while searching utmp for tty (null)
Sep  4 05:31:51 wombat pam_usb[188024]: Couldn't retrieve login tty, assuming remote
Sep  4 05:31:51 wombat pam_usb[188024]: Couldn't confirm login tty to be neither local or remote - denying.
Sep  4 05:31:51 wombat pam_usb[188024]: Access denied.
```

**Comment by mcdope** [comment] 2022-09-04 12:50
This will indeed be very likely related since no method to obtain the tty worked in that try. Guess if loginctl wouldn't bug out for you it would work. 

Let's see again after #180 is fixed

**Comment by mcdope** [comment] 2022-09-06 13:25
Since you reported that loginctl does not return a tty (https://github.com/mcdope/pam_usb/issues/180#issuecomment-1236432816) I guess this is NOT caused by #180.

Can you please provide the output of `w` and `who` too?

**Comment by steelsnake** [comment] 2022-09-07 06:26
From console:
```
[00:20:52] jenni@wombat:~$ w
 00:20:54 up 6 days,  4:56,  3 users,  load average: 1.07, 0.87, 0.41
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
jenni    tty1     :0               00:15    6days  8.81s  0.28s /usr/bin/startplasma-x11
jenni    pts/0    :0               00:15    5:02   0.00s  1.48s /usr/bin/kded5
jenni    pts/1    :0               00:20    2.00s  0.01s  0.00s w
[00:20:54] jenni@wombat:~$ who
jenni    tty1         2022-09-07 00:15 (:0)
jenni    pts/0        2022-09-07 00:15 (:0)
jenni    pts/1        2022-09-07 00:20 (:0)

```

From the lockscreen (I added it as a KDE event on screen lock):
```
[00:21:07] jenni@wombat:~$ cat w.txt
 00:23:55 up 6 days,  4:59,  3 users,  load average: 0.90, 0.86, 0.48
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
jenni    tty1     :0               00:15    6days 12.02s  0.28s /usr/bin/startplasma-x11
jenni    pts/0    :0               00:15    8:03   0.00s  1.62s /usr/bin/kded5
jenni    pts/1    :0               00:20    2:48   0.01s  0.01s /bin/bash
[00:24:54] jenni@wombat:~$ cat who.txt 
jenni    tty1         2022-09-07 00:15 (:0)
jenni    pts/0        2022-09-07 00:15 (:0)
jenni    pts/1        2022-09-07 00:20 (:0)
```

**Comment by mcdope** [comment] 2022-09-07 10:25
Thanks! 

Which distribution are you using? I would like to reproduce your setup as closely as possible for testing in a VM.

**Comment by mcdope** [comment] 2022-09-07 15:12
Should be fixed with unsigned builds from https://www.dropbox.com/sh/mwr7ia5ixk3199m/AACEAPOBSjBojcwaLPNsGddPa?dl=0 / branch `issue-181-fix-kde-lockscreen-being-remote-blocked`

**Comment by steelsnake** [comment] 2022-09-08 00:43
Yep that's fixed too with the new build :+1:  Thank you!

I have two machines I use, both running Kubuntu 22.04. One has backports enabled, the other doesn't.

If you ever do want me to test any builds do feel free to tag me.

**Closed** 2022-09-08 15:24 UTC
Labels: bug
