### ISSUE TITLE
[Packaging] [Debian] Package configuration chooses the wrong device

### ISSUE THREAD

**Issue by Cistoge** [mcdope/pam_usb#102] opened 2021-12-18 12:06 UTC
Hello,

I  downloaded the source code of latest stable version and built a Debian package for Debian 11 from it. After installing the package, I wondered why pam_usb complained about non-updateable one-time pads and found that this happened because pam_usb had configured itself to use a read-only filesystem on /dev/sda1, though at package installation, in the configuration dialogue I had chosen /dev/sda2 for the one-time pads.

Regards
  Christoph

**Comment by mcdope** [comment] 2021-12-18 12:17
Interesting, never noticed that. But then again, not sure I ever tested with multiple partitions on the device. Will investigate (and filter out read-only fs'es too - no point in having them listed).

**Comment by mcdope** [comment] 2022-04-30 14:45
Finally got around to test it a bit... It seems I've created configuration scripts that support more then pam_usb itself. Since the device is only stored by volume label it will always use the first partition currently.

This should be fixed by storing the devices by UUID I guess...

**Comment by mcdope** [comment] 2022-04-30 14:53
I just tried to reproduced this, using a usb stick partitioned into 2x FAT32 partitions. First I purged the package, made sure the config is gone and then reinstalled - choosing the second partition. 

This worked like expected.  Can you please try again if you can actually reproduce this?

**Comment by mcdope** [comment] 2022-05-21 13:16
Closing because lack of feedback.

**Closed by mcdope** 2022-05-21 13:16 UTC
Labels: bug, waiting-for-feedback
